version: '3.8'

services:
  flask:
    build:
     context: ./backend
    ports:
    - 5000:5000
    volumes:
    - ./backend:/app

  mysqldb:
    image: mysql
    ports:
    - 3307:3306
    environment:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
    - mysql:/var/lib/mysql
    - mysqlconfig:/etc/mysql

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mysql:
  mysqlconfig: